FROM node:9.11.1-alpine AS builder

RUN apk update && apk upgrade && apk add --no-cache git python make g++

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install

FROM node:9.11.1-alpine

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules

COPY . /app

CMD npm run test
