FROM node:15.12.0-alpine AS builder

# This Dockerfile could have been omitted if mounting volumes was working in Jenkins.
# We use this file just so we can copy inside the image the contract mapping json file
# used for testing purposes.
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python \
      git

WORKDIR /opt

COPY package.json package-lock.json* ./

RUN npm ci --verbose
RUN npm cache clean --force

FROM node:15.12.0-alpine

RUN apk --no-cache add libsasl openssl lz4-libs netcat-openbsd coreutils

WORKDIR /opt/app

ENV PATH /opt/node_modules/.bin:$PATH
ENV EXACT_CONTRACT_MODE "1"

COPY . /opt/app

COPY --from=builder /opt/node_modules /opt/node_modules
COPY test/erc20/contract_mapping/ /opt/app/blockchains/erc20/lib/contract_mapping/
EXPOSE 3000

CMD npm test
