FROM node:21.4.0-slim AS builder

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN apt-get update; \
    apt-get install -y bash \
    g++ \
    ca-certificates \
    musl-dev \
    make \
    git \
    python3

WORKDIR /opt

COPY package.json package-lock.json* tsconfig.json ./
COPY src ./src

#RUN if [ "$BUILD_ENV" = "production" ]; \
#    then npm ci && npm prune --production; \
#    else npm ci; \
#    fi && \
#    npm run build && \
#    npm cache clean --force


CMD ["tail", "-f", "/dev/null"]
