FROM node:18.1.0-buster-slim AS builder

# This Dockerfile could have been omitted if mounting volumes was working in Jenkins.
# We use this file just so we can copy inside the image the contract mapping json file
# used for testing purposes.
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN apt-get update; \
    apt-get install -y bash \
      g++ \
      ca-certificates \
      musl-dev \
      make \
      git \
      python3

WORKDIR /opt

COPY package.json package-lock.json* ./

RUN npm ci --verbose
RUN npm cache clean --force

FROM node:18.1.0-buster-slim

RUN apt-get update; \
    apt-get install -y openssl netcat-openbsd

WORKDIR /opt/app

ENV PATH /opt/node_modules/.bin:$PATH
ENV CONTRACT_MODE "extract_exact_overwrite"

COPY . /opt/app

COPY --from=builder /opt/node_modules /opt/node_modules
COPY test/erc20/contract_mapping/ /opt/app/blockchains/erc20/lib/contract_mapping/
EXPOSE 3000

CMD npm test
