const BLOCKCHAIN = process.env.BLOCKCHAIN;
const CONFIG_PATH = process.env.CONFIG_PATH;
const EXPORT_BLOCKS_LIST = process.env.EXPORT_BLOCKS_LIST || false;
const PQUEUE_MAX_SIZE = parseInt(process.env.PQUEUE_MAX_SIZE || 100);
const MAX_CONCURRENT_REQUESTS = parseInt(process.env.MAX_CONCURRENT_REQUESTS || 1);
const EXPORT_TIMEOUT_MLS = parseInt(process.env.EXPORT_TIMEOUT_MLS) || 1000 * 60 * 5; // 5 minutes
const EXPORT_BLOCKS_LIST_MAX_INTERVAL = parseInt(process.env.EXPORT_BLOCKS_LIST_MAX_INTERVAL) || 50;

module.exports = {
  BLOCKCHAIN,
  CONFIG_PATH,
  PQUEUE_MAX_SIZE,
  EXPORT_BLOCKS_LIST,
  EXPORT_TIMEOUT_MLS,
  MAX_CONCURRENT_REQUESTS,
  EXPORT_BLOCKS_LIST_MAX_INTERVAL
};
